apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: comments
  name: comments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: comments
    spec:
      containers:
      - image: gagabrielala10/comments_api:latest
        name: comments-api
        resources: {}
status: {}