name: Docker Image CI

on:
  push:
    branches:
      - cicd
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t DOCKER_USER/comments_api:${{ github.sha }}
    - name: Push image
      run: |
        docker login -u $DOCKER_USER -p$DOCKER_PASSWORD
        docker push $DOCKER_USER/comments_api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Update deploy version
      run: sed -i "s/:latest/:${{ github.sha }}/" kube-gcp/kube/deployment.yaml
    - name: Install the gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: comments-440520
        install_components: 'gke-gcloud-auth-plugin'
    - name: Deploy to GKE
      run: kubectl --kubeconfig kube-gcp/terraform/kubeconfig.yaml apply -k kube-gcp/kube