name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Create kubeconfig file
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./kube-gcp/terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Format
      run: terraform fmt -check
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      working-directory: ./kube-gcp/terraform

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      working-directory: ./kube-gcp/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      working-directory: ./kube-gcp/terraform
